<?php

namespace AppBundle\Repository;

/**
 * VmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VmRepository extends \Doctrine\ORM\EntityRepository
{
}
